config_PEMS03:
  pos_dim: 96
  embed_dim: 96
  num_heads: 8
  encoder_depth: 2
  mlp_ratio: 1
  dropout: 0.2

  # diffusion parameters
  num_steps: 50
  schedule: "quad"
  num_sample: 8
  objective: "noise" # input or noise

  # wavenet parameters
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2

config_PEMSBAY:
  pos_dim: 96
  embed_dim: 96
  num_heads: 8
  encoder_depth: 2
  mlp_ratio: 1
  dropout: 0.2

  # diffusion parameters
  num_steps: 50
  schedule: "quad"
  num_sample: 8
  objective: "noise" # input or noise

  # wavenet parameters
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2

config_BJAir:
  pos_dim: 96
  embed_dim: 96
  num_heads: 8
  encoder_depth: 2
  mlp_ratio: 1
  dropout: 0.2

  # diffusion parameters
  num_steps: 50
  schedule: "quad"
  num_sample: 8
  objective: "noise" # input or noise

  # wavenet parameters
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2

config_GZAir:
  pos_dim: 96
  embed_dim: 96
  num_heads: 8
  encoder_depth: 2
  mlp_ratio: 1
  dropout: 0.2

  # diffusion parameters
  num_steps: 50
  schedule: "quad"
  num_sample: 8
  objective: "input" # input or noise

  # wavenet parameters
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2
  
  config_BJINFLOW01:
  pos_dim: 96
  embed_dim: 96
  num_heads: 8
  encoder_depth: 2
  mlp_ratio: 1
  dropout: 0.2

  # diffusion parameters
  num_steps: 50
  schedule: "quad"
  num_sample: 50
  objective: "noise" # input or noise

  # wavenet parameters
  wavenet:
    embed_dim: 32
    end_dim: 64
    mask_ratio: 0.75
    dropout: 0.2